/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as IptvTestRouteImport } from './routes/iptv-test'
import { Route as IptvKaufenRouteImport } from './routes/iptv-kaufen'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BesterIptvAnbieterRouteImport } from './routes/bester-iptv-anbieter'
import { Route as AutorRouteImport } from './routes/autor'
import { Route as Abonnement6MonateRouteImport } from './routes/abonnement-6-monate'
import { Route as Abonnement3MonateRouteImport } from './routes/abonnement-3-monate'
import { Route as Abonnement24MonateRouteImport } from './routes/abonnement-24-monate'
import { Route as Abonnement12MonateRouteImport } from './routes/abonnement-12-monate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiPublicBlogCronRouteImport } from './routes/api/public/blog-cron'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const IptvTestRoute = IptvTestRouteImport.update({
  id: '/iptv-test',
  path: '/iptv-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IptvKaufenRoute = IptvKaufenRouteImport.update({
  id: '/iptv-kaufen',
  path: '/iptv-kaufen',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BesterIptvAnbieterRoute = BesterIptvAnbieterRouteImport.update({
  id: '/bester-iptv-anbieter',
  path: '/bester-iptv-anbieter',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorRoute = AutorRouteImport.update({
  id: '/autor',
  path: '/autor',
  getParentRoute: () => rootRouteImport,
} as any)
const Abonnement6MonateRoute = Abonnement6MonateRouteImport.update({
  id: '/abonnement-6-monate',
  path: '/abonnement-6-monate',
  getParentRoute: () => rootRouteImport,
} as any)
const Abonnement3MonateRoute = Abonnement3MonateRouteImport.update({
  id: '/abonnement-3-monate',
  path: '/abonnement-3-monate',
  getParentRoute: () => rootRouteImport,
} as any)
const Abonnement24MonateRoute = Abonnement24MonateRouteImport.update({
  id: '/abonnement-24-monate',
  path: '/abonnement-24-monate',
  getParentRoute: () => rootRouteImport,
} as any)
const Abonnement12MonateRoute = Abonnement12MonateRouteImport.update({
  id: '/abonnement-12-monate',
  path: '/abonnement-12-monate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiPublicBlogCronRoute = ApiPublicBlogCronRouteImport.update({
  id: '/api/public/blog-cron',
  path: '/api/public/blog-cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnement-12-monate': typeof Abonnement12MonateRoute
  '/abonnement-24-monate': typeof Abonnement24MonateRoute
  '/abonnement-3-monate': typeof Abonnement3MonateRoute
  '/abonnement-6-monate': typeof Abonnement6MonateRoute
  '/autor': typeof AutorRoute
  '/bester-iptv-anbieter': typeof BesterIptvAnbieterRoute
  '/blog': typeof BlogRouteWithChildren
  '/iptv-kaufen': typeof IptvKaufenRoute
  '/iptv-test': typeof IptvTestRoute
  '/preise': typeof PreiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/public/blog-cron': typeof ApiPublicBlogCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnement-12-monate': typeof Abonnement12MonateRoute
  '/abonnement-24-monate': typeof Abonnement24MonateRoute
  '/abonnement-3-monate': typeof Abonnement3MonateRoute
  '/abonnement-6-monate': typeof Abonnement6MonateRoute
  '/autor': typeof AutorRoute
  '/bester-iptv-anbieter': typeof BesterIptvAnbieterRoute
  '/blog': typeof BlogRouteWithChildren
  '/iptv-kaufen': typeof IptvKaufenRoute
  '/iptv-test': typeof IptvTestRoute
  '/preise': typeof PreiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/public/blog-cron': typeof ApiPublicBlogCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnement-12-monate': typeof Abonnement12MonateRoute
  '/abonnement-24-monate': typeof Abonnement24MonateRoute
  '/abonnement-3-monate': typeof Abonnement3MonateRoute
  '/abonnement-6-monate': typeof Abonnement6MonateRoute
  '/autor': typeof AutorRoute
  '/bester-iptv-anbieter': typeof BesterIptvAnbieterRoute
  '/blog': typeof BlogRouteWithChildren
  '/iptv-kaufen': typeof IptvKaufenRoute
  '/iptv-test': typeof IptvTestRoute
  '/preise': typeof PreiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/public/blog-cron': typeof ApiPublicBlogCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnement-12-monate'
    | '/abonnement-24-monate'
    | '/abonnement-3-monate'
    | '/abonnement-6-monate'
    | '/autor'
    | '/bester-iptv-anbieter'
    | '/blog'
    | '/iptv-kaufen'
    | '/iptv-test'
    | '/preise'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/api/public/blog-cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnement-12-monate'
    | '/abonnement-24-monate'
    | '/abonnement-3-monate'
    | '/abonnement-6-monate'
    | '/autor'
    | '/bester-iptv-anbieter'
    | '/blog'
    | '/iptv-kaufen'
    | '/iptv-test'
    | '/preise'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/api/public/blog-cron'
  id:
    | '__root__'
    | '/'
    | '/abonnement-12-monate'
    | '/abonnement-24-monate'
    | '/abonnement-3-monate'
    | '/abonnement-6-monate'
    | '/autor'
    | '/bester-iptv-anbieter'
    | '/blog'
    | '/iptv-kaufen'
    | '/iptv-test'
    | '/preise'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/api/public/blog-cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Abonnement12MonateRoute: typeof Abonnement12MonateRoute
  Abonnement24MonateRoute: typeof Abonnement24MonateRoute
  Abonnement3MonateRoute: typeof Abonnement3MonateRoute
  Abonnement6MonateRoute: typeof Abonnement6MonateRoute
  AutorRoute: typeof AutorRoute
  BesterIptvAnbieterRoute: typeof BesterIptvAnbieterRoute
  BlogRoute: typeof BlogRouteWithChildren
  IptvKaufenRoute: typeof IptvKaufenRoute
  IptvTestRoute: typeof IptvTestRoute
  PreiseRoute: typeof PreiseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicBlogCronRoute: typeof ApiPublicBlogCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iptv-test': {
      id: '/iptv-test'
      path: '/iptv-test'
      fullPath: '/iptv-test'
      preLoaderRoute: typeof IptvTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iptv-kaufen': {
      id: '/iptv-kaufen'
      path: '/iptv-kaufen'
      fullPath: '/iptv-kaufen'
      preLoaderRoute: typeof IptvKaufenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bester-iptv-anbieter': {
      id: '/bester-iptv-anbieter'
      path: '/bester-iptv-anbieter'
      fullPath: '/bester-iptv-anbieter'
      preLoaderRoute: typeof BesterIptvAnbieterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autor': {
      id: '/autor'
      path: '/autor'
      fullPath: '/autor'
      preLoaderRoute: typeof AutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement-6-monate': {
      id: '/abonnement-6-monate'
      path: '/abonnement-6-monate'
      fullPath: '/abonnement-6-monate'
      preLoaderRoute: typeof Abonnement6MonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement-3-monate': {
      id: '/abonnement-3-monate'
      path: '/abonnement-3-monate'
      fullPath: '/abonnement-3-monate'
      preLoaderRoute: typeof Abonnement3MonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement-24-monate': {
      id: '/abonnement-24-monate'
      path: '/abonnement-24-monate'
      fullPath: '/abonnement-24-monate'
      preLoaderRoute: typeof Abonnement24MonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement-12-monate': {
      id: '/abonnement-12-monate'
      path: '/abonnement-12-monate'
      fullPath: '/abonnement-12-monate'
      preLoaderRoute: typeof Abonnement12MonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/public/blog-cron': {
      id: '/api/public/blog-cron'
      path: '/api/public/blog-cron'
      fullPath: '/api/public/blog-cron'
      preLoaderRoute: typeof ApiPublicBlogCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Abonnement12MonateRoute: Abonnement12MonateRoute,
  Abonnement24MonateRoute: Abonnement24MonateRoute,
  Abonnement3MonateRoute: Abonnement3MonateRoute,
  Abonnement6MonateRoute: Abonnement6MonateRoute,
  AutorRoute: AutorRoute,
  BesterIptvAnbieterRoute: BesterIptvAnbieterRoute,
  BlogRoute: BlogRouteWithChildren,
  IptvKaufenRoute: IptvKaufenRoute,
  IptvTestRoute: IptvTestRoute,
  PreiseRoute: PreiseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicBlogCronRoute: ApiPublicBlogCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
